# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
workspace 'TinderCat'

def rxPods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
end

def uiPods
  pod 'Koloda'
  pod 'Kingfisher'
end


target 'TinderCat' do
  rxPods
  uiPods
  pod 'Runtime'
  
  target 'Services' do
    inherit! :search_paths
    project 'Services/Services.project'
  end
  
  target 'MainCardsView' do
    inherit! :search_paths
    project 'MainCardsView/MainCardsView.project'
  end
  
  target 'CatCore' do
    inherit! :search_paths
    project 'CatCore/CatCore.project'
  end
  
  target 'CoreDataService' do
    inherit! :search_paths
    project 'CoreDataService/CoreDataService.project'
  end

  target 'TinderCatUITests' do
  end

end

###### Post install configs ######
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
